#!/bin/bash

ip="google.com"
count=1

while [ true ]; do
     png=$(ping -c ${count} ${ip} 2<&1)
     result1=$(echo "$png" | grep -icE 'unknown|expired|unreachable|time out') 
     result2=$(echo "$png" | grep 'time=' | grep -o 'time=[^"]*' | grep -oE '\b[0-9]{1,3}(\.[0-9]{1,3}){1}\b')

     if [ "$result1" = 0 ]
      then
       mosquitto_pub -t segnetics/server1/ping  -r  -m "$result2"
      else	
       mosquitto_pub -t segnetics/server1/ping  -r  -m "0"
     fi 
     sleep 5
done
